export const APP_NAME = "Dovu Labs";
export const APP_DESC = "Hedera22";
export const APP_ICON = "NA";
export const DAPP = { name: APP_NAME, description: APP_DESC, icon: APP_ICON };
export const LOCAL_STORAGE_KEY = "wallet";
export const NETWORK = "testnet";
export const CONTRACT_ID = "0.0.34737220"; //"0.0.34400935";
export const CONTRACT_OWNER = "0.0.34095176"; // TODO: Keep hardcoded to replace getIsOwner?
export const TOKEN_ID = "0.0.30875555";
export const TOKEN_EXP = 10**6; // TODO: get data from mirror node & create function to correctly display precision.
export const TOKEN_NAME = "testDOV"; // TODO: get data from mirror node.